### ISSUE TITLE
Error: Cannot find module 'pilite'

### ISSUE THREAD

**Issue by rubenvde** [woodyrew/node-pilite#4]
install is working correctly but cannot find the module. I run the install a couple times but it won't work. Can somebody help me?

**Comment by woodyrew** [comment]
I'm assuming you are using this on a Raspberry Pi, have `node` and `npm` installed and are connected to the internet.

Is it the following command that fails?

```
$ npm install pilite
```

Could you provide the contents of `npm-debug.log` if this is where it's failing.

**Comment by rubenvde** [comment]
It's fixed thank you. My fault
